# This workflow will run lint and tests using node when push or pull_request is created

name: build

on: ["push", "pull_request"]

jobs:
  build:
    name: Lint, test and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run lint
      - run: npm run unit-test
      - name: Coveralls - push
        if: success()
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}